language: "de_core_news_sm"
#pipeline: "spacy_sklearn"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "analytics_engine.social_re_component.SocialRelationExtractor"
